# Generated by Django 5.2.7 on 2025-12-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Capstone', 'Capstone'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack')], default='Frontend', max_length=50),
        ),
    ]
