# Generated by Django 5.2.7 on 2025-12-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('skills', models.CharField(help_text='Comma-separated list of skills', max_length=255)),
            ],
        ),
    ]
